# Bag of Words

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.DataFrame({"text":['people watch youtube','youtube watch youtube',"people write comment","youtube write comment"],"output":[1,1,0,0]})

In [3]:
df

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [5]:
bow=cv.fit_transform(df['text'])

In [6]:
cv.vocabulary_

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comment': 0}

In [7]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 0 1]]
[[0 0 1 0 2]]
[[1 1 0 1 0]]


# N-Grams

In [9]:
df.head()

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [31]:
cv=CountVectorizer(ngram_range=(2,2))

In [32]:
bowb=cv.fit_transform(df['text'])

In [38]:
cv.vocabulary_

{'people watch': 0,
 'watch youtube': 2,
 'youtube watch': 4,
 'people write': 1,
 'write comment': 3,
 'youtube write': 5}

In [41]:
print(bowb[0].toarray())
print(bowb[1].toarray())
print(bowb[2].toarray())
print(bowb[3].toarray())

[[1 0 1 0 0 0]]
[[0 0 1 0 1 0]]
[[0 1 0 1 0 0]]
[[0 0 0 1 0 1]]


In [59]:
cv=CountVectorizer(ngram_range=(2,2))
b=cv.fit_transform(["this movie is very good","this movie is not good"])

In [60]:
cv.vocabulary_

{'this movie': 4,
 'movie is': 2,
 'is very': 1,
 'very good': 5,
 'is not': 0,
 'not good': 3}

In [62]:
print(b[0].toarray())
print(b[1].toarray())

[[0 1 1 0 1 1]]
[[1 0 1 1 1 0]]


# Tf-Idf

In [65]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
t=tfidf.fit_transform(df['text'])

In [67]:
t.toarray()

array([[0.        , 0.61366674, 0.61366674, 0.        , 0.49681612],
       [0.        , 0.        , 0.52546357, 0.        , 0.8508161 ],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612]])

In [68]:
tfidf.idf_

array([1.51082562, 1.51082562, 1.51082562, 1.51082562, 1.22314355])

In [71]:
tfidf.get_feature_names_out()

array(['comment', 'people', 'watch', 'write', 'youtube'], dtype=object)