In [178]:
import numpy as np
import pandas as pd

In [179]:
df=pd.read_csv("c:\\Users\\user\\Datasets\\IMDB Dataset.csv")

In [180]:
df=df.iloc[:10000]

In [181]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [182]:
df['review'][1]

'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well d

In [183]:
df['sentiment'].value_counts()

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [184]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [185]:
df.duplicated().sum()

17

In [186]:
df.drop_duplicates(inplace=True)

In [187]:
df.duplicated().sum()

0

In [188]:
import re
def rt(raw_text):
    cleaned_text=re.sub(re.compile('<.*?>'),"",raw_text)
    return cleaned_text

In [189]:
df['review']=df['review'].apply(rt)

In [190]:
df['review']=df['review'].apply(lambda x:x.lower())

In [191]:
from nltk.corpus import stopwords

sw_list=stopwords.words('english')
df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [192]:
# import nltk
# from nltk.tokenize import sent_tokenize
# from nltk.stem import WordNetLemmatizer
# from nltk.corpus import wordnet

# lemmatizer = WordNetLemmatizer()
# def get_wordnet_pos(tag):
#     if tag.startswith('J'):
#         return wordnet.ADJ
#     elif tag.startswith('V'):
#         return wordnet.VERB
#     elif tag.startswith('N'):
#         return wordnet.NOUN
#     elif tag.startswith('R'):
#         return wordnet.ADV
#     else:
#         return None
# def lematize(text):
#     tokens = nltk.word_tokenize(text)
#     pos_tags = nltk.pos_tag(tokens)
#     lemmatized = []
#     for token, tag in pos_tags:
#         wordnet_pos = get_wordnet_pos(tag) or wordnet.NOUN
#         lemmatized.append(lemmatizer.lemmatize(token, pos=wordnet_pos))
#     return " ".join(lemmatized)
    

In [193]:
# df['review']=df['review'].apply(lematize)

In [194]:
df.head()

review sentiment
0  one reviewers mentioned watching 1 oz episode ...  positive
1  wonderful little production. filming technique...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically there's family little boy (jake) thi...  negative
4  petter mattei's "love time money" visually stu...  positive

In [195]:
x=df.iloc[:,0:1]
y=df['sentiment']

In [196]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)

In [197]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [198]:
print(x_train.shape)
print(x_test.shape)


(7986, 1)
(1997, 1)


In [199]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x_train_bow=cv.fit_transform(x_train['review']).toarray()
x_test_bow=cv.transform(x_test['review']).toarray()
x_train_bow.shape
x_test_bow.shape



(1997, 48247)

In [200]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train_bow,y_train)

GaussianNB()

In [201]:
y_pred=gnb.predict(x_test_bow)

In [203]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))

0.627941912869304


In [204]:
confusion_matrix(y_test,y_pred)

array([[694, 291],
       [452, 560]], dtype=int64)

In [205]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train_bow,y_train)

RandomForestClassifier()

In [206]:
y_pred=rf.predict(x_test_bow)

In [207]:
accuracy_score(y_test,y_pred)

0.8517776664997496

In [208]:
confusion_matrix(y_test,y_pred)

array([[841, 144],
       [152, 860]], dtype=int64)

# Using Word2vec

In [224]:
import numpy as np
import pandas as pd

In [225]:
df=pd.read_csv("c:\\Users\\user\\Datasets\\IMDB Dataset.csv")

In [226]:
df=df.iloc[:10000]

In [237]:
df.info

<bound method DataFrame.info of                                                  review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[10000 rows x 2 columns]>

In [238]:
df.drop_duplicates(inplace=True)

In [239]:
df['review']=df['review'].apply(lambda x:x.lower())

In [240]:
df['review']=df['review'].apply(rt)

In [241]:
from nltk.corpus import stopwords

sw_list=stopwords.words('english')
df['review']=df['review'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [242]:
import gensim

In [243]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess # preprocess data

story=[]

for doc in df['review']:    
    raw_sent = sent_tokenize(doc)
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [244]:
len(story)

105773

In [245]:
model = Word2Vec(
    window=10,
    min_count=2,
)

In [246]:
model.build_vocab(story)

In [247]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(5875685, 6212140)

In [251]:
len(model.wv.index_to_key)

31845

In [252]:
def document_vector(doc):
    doc=[word for word in doc.split() if word in model.wv.index_to_key]
    return np.mean(model.wv[doc],axis=0)

In [253]:
document_vector(df['review'].values[0])

array([-1.51486367e-01,  4.31629747e-01,  1.22874878e-01,  2.37887830e-01,
       -9.17612016e-02, -6.03469908e-01,  1.74839795e-01,  9.10030127e-01,
       -4.13776636e-01, -2.74382025e-01, -2.86216289e-01, -4.76859719e-01,
        5.03997952e-02,  8.95193294e-02,  2.16505513e-01, -1.59760162e-01,
       -4.76599112e-03, -3.24785501e-01, -8.00090879e-02, -6.24523580e-01,
        2.82217320e-02,  2.78160334e-01,  1.32394701e-01, -2.19214499e-01,
       -3.44201624e-01, -5.91992924e-04, -3.15476507e-01,  1.04247835e-02,
       -3.40966165e-01,  6.63273111e-02,  3.22822154e-01, -5.24874702e-02,
        2.04576641e-01, -2.88931966e-01, -2.14977235e-01,  4.55201119e-01,
        1.06976062e-01, -3.47322345e-01, -2.14311749e-01, -7.29395807e-01,
        1.45535186e-01, -2.52968162e-01,  6.49147108e-02, -9.49935839e-02,
        5.52665472e-01, -1.20840922e-01, -1.95797861e-01, -2.47678813e-02,
        9.61829349e-02,  3.67787361e-01,  3.34936306e-02, -4.19829607e-01,
       -4.15888160e-01, -

In [254]:
from tqdm import tqdm

In [255]:
x=[]
for doc in tqdm(df['review'].values):
    x.append(document_vector(doc))

100%|██████████████████████████████████████████████████████████████████████████████| 9983/9983 [06:49<00:00, 24.35it/s]


In [256]:
x=np.array(x)

In [257]:
x.shape

(9983, 100)

In [258]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
y=lb.fit_transform(y)

In [259]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [260]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [262]:
y_pred=gnb.predict(x_test)

In [263]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))

0.728092138207311


In [266]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)

In [267]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))

0.7811717576364546
